meta_product_name: "Fancier"
meta_title: "Fancier | share the glitter, not the litter"
meta_description: "the global marketplace for vintage festival outfits. original, sustainable, fancier."
meta_image: "cover.png" # should exist in `app/assets/images/`
